# sdfm/flight/mavlink_router.py

from __future__ import annotations

import queue
import threading
import time
from typing import Any, Callable

from sdfm.flight.pixhawk import PixhawkConnection
from sdfm.flight.telemetry import TelemetryState


DEFAULT_IDLE_SLEEP_SEC = 0.01


class MavlinkRouter:
    """
    Single owner of the MAVLink receive path.

    Responsibilities:
    - read MAVLink messages from Pixhawk
    - update TelemetryState
    - route COMMAND_ACK messages to an ACK queue
    - allow future subscribers for specific message types

    Important:
    No other production component should call recv_match()
    directly while this router is running.
    """

    def __init__(
        self,
        pixhawk: PixhawkConnection,
        telemetry: TelemetryState,
    ) -> None:

        self.pixhawk = pixhawk
        self.telemetry = telemetry

        self._running = False

        self._thread: threading.Thread | None = None

        self._ack_queue: queue.Queue[Any] = queue.Queue()

        self._subscribers: dict[
            str,
            list[Callable[[Any], None]],
        ] = {}

        self._subscriber_lock = threading.RLock()

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    @property
    def running(self) -> bool:
        return self._running

    def start(self) -> None:
        """
        Start background MAVLink receiver.

        Pixhawk must already be connected.
        """

        if self._running:
            return

        if not self.pixhawk.connected:
            raise RuntimeError(
                "PIXHAWK_NOT_CONNECTED"
            )

        self._running = True

        self._thread = threading.Thread(
            target=self._run,
            name="sdfm-mavlink-router",
            daemon=True,
        )

        self._thread.start()

    def stop(
        self,
        timeout_sec: float = 2.0,
    ) -> None:
        """
        Stop background receiver.
        """

        self._running = False

        thread = self._thread

        if thread is not None:
            thread.join(
                timeout=timeout_sec
            )

        self._thread = None

    # ------------------------------------------------------------------
    # Main receive loop
    # ------------------------------------------------------------------

    def _run(self) -> None:
        """
        Receive MAVLink messages continuously.

        This is the only production receive loop.
        """

        while self._running:

            try:
                message = self.pixhawk.recv_match(
                    blocking=False,
                )

            except Exception:
                #
                # Connection-loss handling will later be integrated
                # with Safety Manager / event system.
                #
                time.sleep(
                    DEFAULT_IDLE_SLEEP_SEC
                )
                continue

            if message is None:
                time.sleep(
                    DEFAULT_IDLE_SLEEP_SEC
                )
                continue

            self._route_message(
                message
            )

    # ------------------------------------------------------------------
    # Routing
    # ------------------------------------------------------------------

    def _route_message(
        self,
        message: Any,
    ) -> None:

        message_type = message.get_type()

        #
        # BAD_DATA is generated by pymavlink when a stream contains
        # bytes that cannot be decoded as a valid MAVLink packet.
        #
        if message_type == "BAD_DATA":
            return

        # --------------------------------------------------------------
        # Telemetry
        # --------------------------------------------------------------

        self.telemetry.update(
            message
        )

        # --------------------------------------------------------------
        # COMMAND_ACK
        # --------------------------------------------------------------

        if message_type == "COMMAND_ACK":
            self._ack_queue.put(
                message
            )

        # --------------------------------------------------------------
        # Subscribers
        # --------------------------------------------------------------

        self._notify_subscribers(
            message_type,
            message,
        )

    # ------------------------------------------------------------------
    # COMMAND_ACK
    # ------------------------------------------------------------------

    def wait_command_ack(
        self,
        command_id: int,
        timeout_sec: float,
    ) -> Any | None:

        deadline = time.monotonic() + timeout_sec
        unmatched: list[Any] = []

        try:
            while True:

                remaining = deadline - time.monotonic()

                if remaining <= 0:
                    return None

                try:
                    ack = self._ack_queue.get(                        timeout=remaining                    )

                except queue.Empty:
                    return None

                if ack.command == command_id:
                    return ack

                unmatched.append(ack)

        finally:
            for item in unmatched:
                self._ack_queue.put(item)

    def clear_ack_queue(self) -> None:
        """
        Clear queued COMMAND_ACK messages.

        Intended mainly for diagnostics / startup cleanup.

        Do not routinely clear this queue while commands are active.
        """

        while True:

            try:
                self._ack_queue.get_nowait()

            except queue.Empty:
                break

    # ------------------------------------------------------------------
    # Subscribers
    # ------------------------------------------------------------------

    def subscribe(
        self,
        message_type: str,
        callback: Callable[[Any], None],
    ) -> None:
        """
        Subscribe callback to a MAVLink message type.

        Example:
            router.subscribe(
                "STATUSTEXT",
                on_status_text,
            )
        """

        with self._subscriber_lock:

            callbacks = self._subscribers.setdefault(
                message_type,
                [],
            )

            if callback not in callbacks:
                callbacks.append(
                    callback
                )

    def unsubscribe(
        self,
        message_type: str,
        callback: Callable[[Any], None],
    ) -> None:

        with self._subscriber_lock:

            callbacks = self._subscribers.get(
                message_type
            )

            if not callbacks:
                return

            try:
                callbacks.remove(
                    callback
                )

            except ValueError:
                return

            if not callbacks:
                self._subscribers.pop(
                    message_type,
                    None,
                )

    def _notify_subscribers(
        self,
        message_type: str,
        message: Any,
    ) -> None:

        with self._subscriber_lock:
            callbacks = list(
                self._subscribers.get(
                    message_type,
                    [],
                )
            )

        for callback in callbacks:

            try:
                callback(
                    message
                )

            except Exception:
                #
                # One subscriber must never kill the MAVLink router.
                # Logging will be added later.
                #
                continue